### ISSUE TITLE
Some users don't have label [Apparently it's expirated user]

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-android#409]
![image](https://user-images.githubusercontent.com/1238254/152332604-f3a5a7fd-c718-4bea-b8b3-a98b762bef40.png)
In this image, the first 3 users don't have domaine label.

**Comment by giomfo** [comment]
@jdauphant we don't have label for these contacts because their profile information are locally missing
Contrary to Element-Android, we use a fallback to build their display name from their matrix id. This method is not able to extract the label (domain), and this will not be fixed (this is a known limitation of the use of '-' character in matrix id)

The profile information of these contacts are due to the fact they left all the rooms you share with them (eventually they deactivated their account). I think Element-Android should remove this kind of contact from the known users list

I keep open this issue for that purpose : "remove from the known users all the contacts who left my rooms"

**Comment by jdauphant** [comment]
If they will be searchable in cas they exist, we can hide them is the account is expired or disabled.

**Comment by giomfo** [comment]
> If they will be searchable in cas they exist, we can hide them is the account is expired or disabled.

FYI this is already the case for the users directory (remote one). We should just have to check this point for the local data handling
