### ISSUE TITLE
Receiving a voice message

### ISSUE THREAD

**Issue by Claire1817** [tchapgouv/tchap-android#609]
Actually in Tchap we can't send a voice message but we can get one if it's send from Element.
![Screenshot_1654177034](https://user-images.githubusercontent.com/15031750/171641916-aa76a0f1-1f1d-4bc4-b5f3-ec0c26816846.png)
The antivirus doesn't analyze the file.

**Comment by giomfo** [comment]
we should check together the question about display or not the received voice messages

**Comment by jdc-anssi** [comment]
Hello Guillaume, 

First, and this is comment is valid for all this kind of situations : the disabling of a functionality means :
- the client doesn't accept any messages from the server or other clients about the functionality;
- the client doesn't send any messages from the server or other clients about the functionality;
- the server doesn't accept any messages from an other server (federation) or other clients about the functionality;
- the server doesn't send any messages from an other server (federation) or other clients about the functionality.

It is important because it is really difficult to evaluate de attack surface of a product if its behavior doesn't fit this definition.
Unfortunatelly, the development practices of Element don't follow this rule for some functionality "disabling" in TChap.

Second, this question is more for the DINUM than me because it's a question about which functionalities the DINUM wants in its products.

Regards,

Jean-Dominique Charot
