### ISSUE TITLE
Verification request from Tartine asks for QR code

### ISSUE THREAD

**Issue by estellecomment** [tchapgouv/tchap-android#680]
### Steps to reproduce

Don't know if this is a bug or if it's expected :)

I have a verified session in tartine.
I have an unverified session in android 2.3.2
I request verification of the android session from tartine
Android displays the verification request.

### Outcome

Expected : verify by emoji
Obtained : verify by QR code (and emoji as a backup)
![Photo on 7-13-22 at 17 12](https://user-images.githubusercontent.com/911434/178781685-f8159d76-f100-45ba-af03-2e3487e9317b.jpg)

Tartine also displays QR code or emoji options.

### Will you send logs?

No

**Comment by Florian14** [comment]
This is because you've connected your account through Element, this is a side effect due to the cross-signing activation which is not available on Tchap synapse. We won't fix it until this is not directly a Tchap issue.

By the way, it will be potentially fixed when the cross signing will be activated for Tchap.
